
export type Quote = {
  text: string;
  author: string;
};

export const catholicQuotes: Quote[] = [
  { text: "La medida del amor es amar sin medida.", author: "San Agustín" },
  { text: "El que no vive para servir, no sirve para vivir.", author: "San Juan Bosco" },
  { text: "Tarde te amé, hermosura tan antigua y tan nueva, tarde te amé.", author: "San Agustín" },
  { text: "Prefiero el paraíso.", author: "Santo Domingo Savio" },
  { text: "Reza, espera y no te preocupes.", author: "San Pío de Pietrelcina" },
  { text: "La oración es la mejor arma que tenemos; es la llave al corazón de Dios.", author: "San Pío de Pietrelcina" },
  { text: "Quien canta, ora dos veces.", author: "San Agustín" },
  { text: "No hay que tener miedo. ¡Abrid de par en par las puertas a Cristo!", author: "San Juan Pablo II" },
  { text: "El amor todo lo puede.", author: "Santa Teresa de Jesús" },
  { text: "La fe es el principio de la salvación; el amor, su fin.", author: "Santo Tomás de Aquino" },
  { text: "Haced el bien mientras tengáis tiempo.", author: "San Juan Bosco" },
  { text: "Confía en Dios, que no dejará de ayudarte.", author: "Santa Teresa de Jesús" },
  { text: "No te dejes vencer por el mal; al contrario, vence el mal con el bien.", author: "San Pablo" },
  { text: "Nuestra vida es un instante en la eternidad.", author: "San Francisco de Sales" },
  { text: "Dios no manda cosas imposibles, sino que, al mandar lo que manda, te invita a hacer lo que puedas.", author: "San Agustín" },
  { text: "Si quieres ser perfecto, ve, vende tus bienes y dáselos a los pobres.", author: "Mt 19, 21" },
  { text: "Para mí, la oración es un impulso del corazón, una sencilla mirada al cielo.", author: "Santa Teresita de Lisieux" },
  { text: "La paciencia es la compañera de la sabiduría.", author: "San Agustín" },
  { text: "El que a Dios tiene, nada le falta; sólo Dios basta.", author: "Santa Teresa de Ávila" },
  { text: "Donde no hay amor, pon amor y sacarás amor.", author: "San Juan de la Cruz" },
  { text: "Comienza haciendo lo que es necesario, después lo que es posible y de repente estarás haciendo lo imposible.", author: "San Francisco de Asís" },
  { text: "Predica el Evangelio en todo momento y, cuando sea necesario, usa las palabras.", author: "San Francisco de Asís" },
  { text: "La prueba de si amas a Dios es si amas a tu prójimo.", author: "San Juan Crisóstomo" },
  { text: "La caridad es la reina de las virtudes.", author: "Santo Tomás de Aquino" },
  { text: "El alma que anda en amor, ni cansa ni se cansa.", author: "San Juan de la Cruz" },
  { text: "La humildad es el fundamento de todas las demás virtudes.", author: "San Agustín" },
  { text: "No me mueve, mi Dios, para quererte, el cielo que me tienes prometido.", author: "Soneto anónimo" },
  { text: "En el atardecer de la vida, seremos juzgados en el amor.", author: "San Juan de la Cruz" },
  { text: "El que tiene caridad en su corazón, tiene el cielo en su alma.", author: "San Felipe Neri" },
  { text: "No hay santo sin pasado, ni pecador sin futuro.", author: "San Agustín" },
  { text: "La santidad consiste en hacer la voluntad de Dios con una sonrisa.", author: "Santa Teresa de Calcuta" },
  { text: "La Eucaristía es el pan de cada día que se toma como remedio de nuestra debilidad cotidiana.", author: "San Agustín" },
  { text: "Trabaja como si todo dependiera de ti, pero confía como si todo dependiera de Dios.", author: "San Ignacio de Loyola" },
  { text: "La alegría es el gran secreto de los santos.", author: "San Pier Giorgio Frassati" },
  { text: "Ama y haz lo que quieras.", author: "San Agustín" },
  { text: "La cruz es la escuela del amor.", author: "San Juan Pablo II" },
  { text: "No es el mucho saber lo que harta y satisface al alma, sino el sentir y gustar de las cosas internamente.", author: "San Ignacio de Loyola" },
  { text: "La santidad no consiste en hacer cosas extraordinarias, sino en hacer extraordinariamente bien las cosas ordinarias.", author: "San Josemaría Escrivá" },
  { text: "La fe se refiere a cosas que no se ven, y la esperanza a cosas que no están al alcance de la mano.", author: "Santo Tomás de Aquino" },
  { text: "Espera en el Señor, sé valiente, ten ánimo, espera en el Señor.", author: "Salmo 27, 14" },
  { text: "La oración es la elevación del alma a Dios o la petición a Dios de bienes convenientes.", author: "San Juan Damasceno" },
  { text: "Vale más un alma que el mundo entero.", author: "San Juan María Vianney" },
  { text: "El amor de Dios no consiste en sentir grandes cosas, sino en tener gran desnudez y padecer por el Amado.", author: "San Juan de la Cruz" },
  { text: "A Jesús se va y se 'vuelve' por María.", author: "San Josemaría Escrivá" },
  { text: "Sé para el mundo un libro abierto que hable de Dios.", author: "Santa Edith Stein" },
  { text: "El secreto de la felicidad es la identificación con la voluntad de Dios.", author: "San Alfonso María de Ligorio" },
  { text: "La alegría de un alma se lee en sus ojos.", author: "San Antonio de Padua" },
  { text: "La oración es la fuerza del hombre y la debilidad de Dios.", author: "San Agustín" },
  { text: "El que teme al Señor no tendrá miedo de nada.", author: "Eclesiástico 34, 14" },
  { text: "La humildad es la verdad.", author: "Santa Teresa de Jesús" },
  { text: "Quien no ama ya está muerto.", author: "San Juan Evangelista" },
  { text: "La santidad es la obra del Espíritu Santo en nosotros.", author: "Catecismo de la Iglesia Católica" },
  { text: "Aprovecha el tiempo, porque los días son malos.", author: "San Pablo" },
  { text: "El que encuentra a un amigo, encuentra un tesoro.", author: "Eclesiástico 6, 14" },
  { text: "La esperanza es una virtud teologal, por la que aspiramos al Reino de los cielos y a la vida eterna.", author: "Catecismo de la Iglesia Católica" },
  { text: "El amor es paciente, es servicial; el amor no tiene envidia...", author: "1 Corintios 13, 4" },
  { text: "Para Dios, nada es imposible.", author: "Lc 1, 37" },
  { text: "El Señor es mi pastor, nada me falta.", author: "Salmo 23" },
  { text: "Mi yugo es suave y mi carga ligera.", author: "Mt 11, 30" },
  { text: "Yo estoy con vosotros todos los días hasta el fin del mundo.", author: "Mt 28, 20" },
  { text: "Donde dos o tres están reunidos en mi nombre, allí estoy yo en medio de ellos.", author: "Mt 18, 20" },
  { text: "La fe es garantía de lo que se espera; la prueba de las realidades que no se ven.", author: "Hebreos 11, 1" },
  { text: "Todo lo puedo en Aquel que me conforta.", author: "Filipenses 4, 13" },
  { text: "El gozo del Señor es nuestra fortaleza.", author: "Nehemías 8, 10" },
  { text: "Si Dios está con nosotros, ¿quién estará contra nosotros?", author: "Romanos 8, 31" },
  { text: "El trabajo bien hecho es una oración.", author: "San Josemaría Escrivá" },
  { text: "La Eucaristía es el corazón y la cumbre de la vida de la Iglesia.", author: "Catecismo de la Iglesia Católica" },
  { text: "No te preocupes por el mañana, el mañana se preocupará por sí mismo.", author: "Mt 6, 34" },
  { text: "Sed perfectos como vuestro Padre celestial es perfecto.", author: "Mt 5, 48" },
  { text: "El amor de Dios ha sido derramado en nuestros corazones por el Espíritu Santo que se nos ha dado.", author: "Romanos 5, 5" },
  { text: "Donde hay caridad y amor, allí está Dios.", author: "Canto litúrgico" },
  { text: "La oración es la respiración del alma.", author: "San Gregorio Nacianceno" },
  { text: "La cruz es la puerta estrecha por la que entramos en el cielo.", author: "San Juan de la Cruz" },
  { text: "El que reza se salva, el que no reza se condena.", author: "San Alfonso María de Ligorio" },
  { text: "La Eucaristía es mi autopista al cielo.", author: "San Carlo Acutis" },
  { text: "Estar siempre alegre, hacer el bien y dejar cantar a los gorriones.", author: "San Juan Bosco" },
  { text: "El demonio teme a la gente alegre.", author: "San Juan Bosco" },
  { text: "Un santo triste es un triste santo.", author: "San Francisco de Sales" },
  { text: "Lo que importa es amar.", author: "Santa Teresita de Lisieux" },
  { text: "No dejen que les roben la esperanza.", author: "Papa Francisco" },
  { text: "El verdadero poder es el servicio.", author: "Papa Francisco" },
  { text: "La alegría del Evangelio llena el corazón y la vida entera de los que se encuentran con Jesús.", author: "Papa Francisco" },
  { text: "La familia es la base de la sociedad y el lugar donde las personas aprenden por vez primera los valores que les guían durante toda su vida.", author: "San Juan Pablo II" },
  { text: "La peor prisión es un corazón cerrado.", author: "San Juan Pablo II" },
  { text: "El futuro empieza hoy, no mañana.", author: "San Juan Pablo II" },
  { text: "¡La Iglesia necesita santos!", author: "San Juan Pablo II" },
  { text: "No es el mucho pensar lo que nos une a Dios, sino el mucho amar.", author: "San Josemaría Escrivá" },
  { text: "Que tu vida no sea una vida estéril. —Sé útil. —Deja poso. —Ilumina, con la luminaria de tu fe y de tu amor.", author: "San Josemaría Escrivá" },
  { text: "No digas: 'esa persona me carga'. —Piensa: 'esa persona me santifica'.", author: "San Josemaría Escrivá" },
  { text: "El Rosario es arma poderosa. Empléala con confianza y te maravillarás del resultado.", author: "San Josemaría Escrivá" },
  { text: "Un pequeño acto, hecho por Amor, ¡cuánto vale!", author: "San Josemaría Escrivá" },
  { text: "Soñad y os quedaréis cortos.", author: "San Josemaría Escrivá" },
  { text: "Que busques a Cristo: Que encuentres a Cristo: Que ames a Cristo.", author: "San Josemaría Escrivá" },
  { text: "El que no ama no ha conocido a Dios, porque Dios es amor.", author: "1 Juan 4, 8" },
  { text: "Nosotros amamos, porque él nos amó primero.", author: "1 Juan 4, 19" },
  { text: "La fe, la esperanza y el amor; pero el mayor de ellos es el amor.", author: "1 Corintios 13, 13" },
  { text: "Por encima de todo, vestíos del amor, que es el vínculo perfecto.", author: "Colosenses 3, 14" },
  { text: "Nadie tiene mayor amor que este, que uno ponga su vida por sus amigos.", author: "Juan 15, 13" },
  { text: "La paz comienza con una sonrisa.", author: "Santa Teresa de Calcuta" },
  { text: "No todos podemos hacer grandes cosas, pero podemos hacer pequeñas cosas con gran amor.", author: "Santa Teresa de Calcuta" },
  { text: "El fruto del silencio es la oración. El fruto de la oración es la fe. El fruto de la fe es el amor. El fruto del amor es el servicio.", author: "Santa Teresa de Calcuta" },
  { text: "El contentamiento es la mayor de las riquezas.", author: "San Alberto Hurtado" },
  { text: "Hay que vivir para los demás como Cristo vivió para nosotros.", author: "San Alberto Hurtado" },
  { text: "Mi Misa es mi vida, y mi vida es una Misa prolongada.", author: "San Alberto Hurtado" },
  { text: "Feliz de ser ladrón de vocaciones para Cristo.", author: "San Alberto Hurtado" },
  { text: "Contento, Señor, contento.", author: "San Josemaría Escrivá"},
  { text: "No basta no hacer el mal, es preciso hacer el bien.", author: "San Alberto Hurtado" },
  { text: "Cristo no tiene más manos que las nuestras para construir un mundo donde habite la justicia.", author: "San Alberto Hurtado" },
  { text: "En todo amar y servir.", author: "San Ignacio de Loyola" },
  { text: "Alcanza la excelencia y compártela.", author: "San Ignacio de Loyola" },
  { text: "El amor se ha de poner más en las obras que en las palabras.", author: "San Ignacio de Loyola" },
  { text: "No el mucho saber harta y satisface al ánima, mas el sentir y gustar de las cosas internamente.", author: "San Ignacio de Loyola" },
  { text: "La santidad no es un lujo para unos pocos, sino un simple deber para ti y para mí.", author: "Santa Teresa de Calcuta" },
  { text: "El Señor es mi luz y mi salvación, ¿a quién temeré?", author: "Salmo 27, 1" },
  { text: "Buscad primero el Reino de Dios y su justicia, y todo lo demás se os dará por añadidura.", author: "Mt 6, 33" },
  { text: "Yo soy el Camino, la Verdad y la Vida.", author: "Jn 14, 6" },
  { text: "La oración contemplativa es una mirada de fe, fijada en Jesús.", author: "San Josemaría Escrivá" },
  { text: "Un hombre sin oración es un animal sin razón.", author: "San Josemaría Escrivá" },
  { text: "La vocación cristiana es una vocación a la santidad, en todo momento.", author: "San Josemaría Escrivá" },
  { text: "No me dejes nunca, nunca solo. Guíame, llévame de tu mano. No me sueltes.", author: "San Josemaría Escrivá" },
  { text: "No eres un tornillo de una máquina. Eres una pieza, ¡con sentido!, del único engranaje que puede mover el mundo: la comunión de los santos.", author: "San Josemaría Escrivá" },
  { text: "El minuto heroico. —Es la hora, en punto, de levantarse. Sin vacilación: un pensamiento sobrenatural y... ¡arriba!", author: "San Josemaría Escrivá" },
  { text: "¡Ojalá sepas y quieras —tú también— ser piedra de sillería, y vivir de modo que arrastres a otros, que los muevas, dando el buen ejemplo de tu lealtad!", author: "San Josemaría Escrivá" },
  { text: "La mortificación no es pesimismo, ni tristeza. La mortificación es espíritu de sacrificio.", author: "San Josemaría Escrivá" },
  { text: "El trabajo es para el cristiano una participación en la obra creadora de Dios.", author: "San Josemaría Escrivá" },
  { text: "El que ama de verdad a su patria sabe que la mejor manera de servirla es ser buen cristiano.", author: "San Josemaría Escrivá" },
  { text: "Para un apóstol moderno, una hora de estudio es una hora de oración.", author: "San Josemaría Escrivá" },
  { text: "Acostúmbrate a elevar tu corazón a Dios, en acción de gracias, muchas veces al día.", author: "San Josemaría Escrivá" },
  { text: "El amor a Nuestra Señora es prenda de salvación.", author: "San Josemaría Escrivá" },
  { text: "El amor de Dios es celoso.", author: "San Josemaría Escrivá" },
  { text: "Todo lo que se hace por Amor adquiere hermosura y se engrandece.", author: "San Josemaría Escrivá" },
  { text: "Sé fuerte. Sé viril. Sé hombre. Y después... sé ángel.", author: "San Josemaría Escrivá" },
  { text: "No tengas enemigos. Ten sólo amigos.", author: "San Josemaría Escrivá" },
  { text: "El que pone su confianza en Dios, lo puede todo.", author: "San Josemaría Escrivá" },
  { text: "La santidad está en la lucha, en el saber que tenemos defectos y en tratar heroicamente de evitarlos.", author: "San Josemaría Escrivá" },
  { text: "No se puede separar al hombre de Dios, ni la política de la moral.", author: "San Josemaría Escrivá" },
  { text: "La vida es una continua oración.", author: "San Josemaría Escrivá" },
  { text: "El tiempo es nuestro tesoro, el «dinero» para comprar la eternidad.", author: "San Josemaría Escrivá" },
  { text: "Es menester que seas «hombre de Dios», hombre de vida interior, hombre de oración y de sacrificio.", author: "San Josemaría Escrivá" },
  { text: "No lo olvides: la santidad no está en hacer cosas cada día más difíciles, sino en hacerlas cada día con más amor.", author: "San Josemaría Escrivá" },
  { text: "La soberbia es el peor de los pecados.", author: "San Josemaría Escrivá" },
  { text: "La caridad todo lo cree, todo lo espera, todo lo soporta.", author: "San Josemaría Escrivá" },
  { text: "La oración es el arma más poderosa del cristiano.", author: "San Josemaría Escrivá" },
  { text: "Sé sencillo y la gente te entenderá.", author: "San Josemaría Escrivá" },
  { text: "¡Qué bueno es saber que tenemos un Padre que nos quiere con locura!", author: "San Josemaría Escrivá" },
  { text: "Cuando se ama de verdad, se da todo lo que se tiene.", author: "San Josemaría Escrivá" },
  { text: "Dios no se deja ganar en generosidad.", author: "San Josemaría Escrivá" },
  { text: "La santidad personal no es una cosa abstracta, sino una realidad divina y humana.", author: "San Josemaría Escrivá" },
  { text: "No hay más que un modo de matar el tiempo: perderlo.", author: "San Josemaría Escrivá" },
  { text: "El que no es para Cristo, es contra Cristo.", author: "San Josemaría Escrivá" },
  { text: "La Cruz de cada día. La Cruz en cada uno de nuestros quehaceres.", author: "San Josemaría Escrivá" },
  { text: "Ser santo es ser feliz.", author: "San Josemaría Escrivá" },
  { text: "¡Qué pena dan esas multitudes —altas y bajas, y de en medio— sin norte!.", author: "San Josemaría Escrivá" },
  { text: "Vivir de cara a Dios, por Dios, para Dios.", author: "San Josemaría Escrivá" },
  { text: "El que quiera ser el primero, que sea el servidor de todos.", author: "San Josemaría Escrivá" },
  { text: "Todo para la gloria de Dios.", author: "San Josemaría Escrivá" },
  { text: "La verdadera caridad consiste en ayudar al prójimo a ser santo.", author: "San Josemaría Escrivá" },
  { text: "El cristiano ha de ser sal y luz del mundo.", author: "San Josemaría Escrivá" },
  { text: "La Santa Misa es el centro y la raíz de la vida espiritual del cristiano.", author: "San Josemaría Escrivá" },
  { text: "Hemos de vivir como si todos los días fueran el último.", author: "San Josemaría Escrivá" },
  { text: "El amor es el único que da la verdadera paz al corazón.", author: "San Josemaría Escrivá" },
  { text: "La Voluntad de Dios es que seamos santos.", author: "San Josemaría Escrivá" },
  { text: "Un joven que reza es un joven poderoso.", author: "Papa Francisco" },
  { text: "La misericordia de Dios es más grande que tu pecado.", author: "Papa Francisco" },
  { text: "El mundo nos dice que busquemos el éxito, el poder y el dinero; Dios nos dice que busquemos la humildad, el servicio y el amor.", author: "Papa Francisco" },
  { text: "¡Hagan lío!", author: "Papa Francisco" },
  { text: "Un cristiano sin alegría es o no es cristiano o está enfermo.", author: "Papa Francisco" },
  { text: "Dios nunca se cansa de perdonar, somos nosotros los que nos cansamos de pedir perdón.", author: "Papa Francisco" },
  { text: "La fe no es una luz que disipa todas nuestras tinieblas, sino una lámpara que guía nuestros pasos en la noche.", author: "Papa Francisco" },
  { text: "El hombre que se pone en manos de Dios no se aleja de los demás.", author: "Benedicto XVI" },
  { text: "La verdad no se determina por la mayoría de votos.", author: "Benedicto XVI" },
  { text: "Cada uno de nosotros es el resultado de un pensamiento de Dios. Cada uno de nosotros es querido, cada uno es amado, cada uno es necesario.", author: "Benedicto XVI" },
  { text: "La fe cristiana no es un 'sistema' de creencias, es una persona, es Jesús.", author: "Benedicto XVI" },
  { text: "La libertad no significa que pueda hacer todo lo que quiero. Libertad significa ser una persona de la verdad y para el bien.", author: "Benedicto XVI" },
  { text: "El amor es la única fuerza que puede transformar verdaderamente el mundo.", author: "San Juan Pablo II" },
  { text: "La santidad es el rostro más bello de la Iglesia.", author: "Papa Francisco" },
  { text: "El Señor nos quiere santos y no espera que nos conformemos con una existencia mediocre, aguada, licuada.", author: "Papa Francisco" },
  { text: "La oración es un diálogo con Dios; y en ese diálogo se aprende a vivir.", author: "Benedicto XVI" },
  { text: "¡El Rosario es la oración de mi predilección! Oración maravillosa en su sencillez y en su profundidad.", author: "San Juan Pablo II" },
  { text: "La Iglesia no es una ONG, es una historia de amor.", author: "Papa Francisco" },
  { text: "Pedid y se os dará; buscad y hallaréis; llamad y se os abrirá.", author: "Mt 7, 7" },
  { text: "Ama a tu prójimo como a ti mismo.", author: "Mt 22, 39" },
  { text: "No sólo de pan vive el hombre, sino de toda palabra que sale de la boca de Dios.", author: "Mt 4, 4" },
  { text: "Venid a mí todos los que estáis cansados y agobiados, y yo os aliviaré.", author: "Mt 11, 28" },
  { text: "El que se enaltece será humillado, y el que se humilla será enaltecido.", author: "Lc 14, 11" },
  { text: "¿De qué le sirve al hombre ganar el mundo entero, si pierde su alma?", author: "Mc 8, 36" },
  { text: "Yo soy la vid, vosotros los sarmientos; el que permanece en mí y yo en él, ése da mucho fruto.", author: "Jn 15, 5" },
  { text: "Porque tuve hambre, y me disteis de comer; tuve sed, y me disteis de beber.", author: "Mt 25, 35" },
  { text: "Amad a vuestros enemigos y rogad por los que os persiguen.", author: "Mt 5, 44" },
  { text: "No juzguéis, y no seréis juzgados; no condenéis, y no seréis condenados; perdonad, y seréis perdonados.", author: "Lc 6, 37" },
  { text: "El que esté libre de pecado que tire la primera piedra.", author: "Jn 8, 7" },
  { text: "Yo soy la luz del mundo; el que me sigue, no andará en tinieblas, sino que tendrá la luz de la vida.", author: "Jn 8, 12" },
  { text: "En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.", author: "Jn 16, 33" },
  { text: "Padre, perdónalos, porque no saben lo que hacen.", author: "Lc 23, 34" },
  { text: "En verdad os digo que si no os convertís y os hacéis como niños, no entraréis en el reino de los cielos.", author: "Mt 18, 3" },
  { text: "El que quiera llegar a ser grande entre vosotros, será vuestro servidor.", author: "Mc 10, 43" },
  { text: "Hay más alegría en dar que en recibir.", author: "Hechos 20, 35" },
  { text: "Felices los de corazón limpio, porque ellos verán a Dios.", author: "Mt 5, 8" },
  { text: "Velad y orad, para que no entréis en tentación.", author: "Mt 26, 41" },
  { text: "Si tenéis fe como un grano de mostaza, diréis a este monte: 'Trasládate de aquí allá', y se trasladará.", author: "Mt 17, 20" },
  { text: "No se turbe vuestro corazón; creéis en Dios, creed también en mí.", author: "Jn 14, 1" },
  { text: "No hay vocación más alta que el servicio a los demás.", author: "San Juan Pablo II" },
  { text: "La vida es un viaje, la fe es el itinerario, Dios es el destino.", author: "Benedicto XVI" },
  { text: "Id por todo el mundo y predicad el evangelio a toda criatura.", author: "Mc 16, 15" },
  { text: "Los que confían en el Señor son como el monte Sión: no tiembla, está asentado para siempre.", author: "Salmo 125, 1" },
  { text: "El Señor es mi fuerza y mi escudo; en él confía mi corazón.", author: "Salmo 28, 7" },
  { text: "Aunque pase por un valle tenebroso, ningún mal temeré, porque tú vas conmigo.", author: "Salmo 23, 4" },
  { text: "La palabra de Dios es viva y eficaz, y más cortante que toda espada de dos filos.", author: "Hebreos 4, 12" },
  { text: "El que quiera salvar su vida, la perderá; pero el que pierda su vida por mí y por el Evangelio, la salvará.", author: "Mc 8, 35" },
  { text: "Yo he venido para que tengan vida, y la tengan en abundancia.", author: "Jn 10, 10" },
  { text: "Si permanecéis en mi palabra, seréis verdaderamente mis discípulos; y conoceréis la verdad, y la verdad os hará libres.", author: "Jn 8, 31-32" },
  { text: "La fe mueve montañas.", author: "Cf. Mt 17, 20" },
  { text: "No te digo que perdones hasta siete veces, sino hasta setenta veces siete.", author: "Mt 18, 22" },
  { text: "Dad al César lo que es del César, y a Dios lo que es de Dios.", author: "Mt 22, 21" },
  { text: "El que se humilla será enaltecido.", author: "Lc 18, 14" },
  { text: "No amemos de palabra ni de lengua, sino de obra y de verdad.", author: "1 Juan 3, 18" },
  { text: "La oración es para el alma lo que la lluvia para la tierra.", author: "San Juan María Vianney" },
  { text: "La Eucaristía es el sol de todas las virtudes.", author: "San Francisco de Sales" },
  { text: "La obediencia es la llave de oro que abre las puertas del cielo.", author: "San Felipe Neri" },
  { text: "La vida es un combate, y la oración es nuestra arma.", author: "San Lorenzo de Brindisi" },
  { text: "La perseverancia es la corona de todas las virtudes.", author: "Santo Tomás de Aquino" },
  { text: "El que no está conmigo, está contra mí.", author: "Mt 12, 30" },
  { text: "El Reino de Dios está dentro de vosotros.", author: "Lc 17, 21" },
  { text: "Cuando sientas que no puedes más, recuerda que estás en las manos de Dios.", author: "Anónimo" },
  { text: "Deja que tu fe sea más grande que tus miedos.", author: "Anónimo" },
  { text: "El mundo te ofrece comodidad, pero tú no estás hecho para la comodidad. Estás hecho para la grandeza.", author: "Benedicto XVI" },
  { text: "La verdadera amistad es un tesoro de gran precio.", author: "San Juan Bosco" },
  { text: "La vida sin amor no tiene sentido.", author: "San Juan Pablo II" },
  { text: "La oración es la única cosa que vence a Dios.", author: "Tertuliano" },
  { text: "La gracia de Dios es la que obra en nosotros el querer y el obrar.", author: "Filipenses 2, 13" },
  { text: "El que siembra con lágrimas, cosecha con alegría.", author: "Salmo 126, 5" },
  { text: "El Señor es lento a la ira y grande en misericordia.", author: "Salmo 145, 8" },
  { text: "La humildad es el camino más corto para llegar a Dios.", author: "San Vicente de Paúl" },
  { text: "La oración es la conversación con Dios.", author: "San Clemente de Alejandría" },
  { text: "La castidad es la virtud que hace al hombre semejante a los ángeles.", author: "San Basilio Magno" },
  { text: "El que es fiel en lo poco, también es fiel en lo mucho.", author: "Lc 16, 10" },
  { text: "Donde está tu tesoro, allí estará también tu corazón.", author: "Mt 6, 21" },
  { text: "El Espíritu está pronto, pero la carne es débil.", author: "Mt 26, 41" },
  { text: "La caridad cubre multitud de pecados.", author: "1 Pedro 4, 8" },
  { text: "Todo contribuye al bien de los que aman a Dios.", author: "Romanos 8, 28" },
  { text: "El que no nace de nuevo no puede ver el Reino de Dios.", author: "Jn 3, 3" },
  { text: "Alegraos siempre en el Señor; os lo repito, alegraos.", author: "Filipenses 4, 4" },
  { text: "La vida del cristiano es una continua Cuaresma.", author: "San Antonio de Padua" },
  { text: "La mejor oración es la que está más llena de amor.", author: "Santa Teresa de Calcuta" },
  { text: "La santidad es la aventura más grande.", author: "San Juan Pablo II" },
  { text: "La Iglesia vive de la Eucaristía.", author: "San Juan Pablo II" },
  { text: "La oración es la llave de los tesoros de Dios.", author: "San Juan María Vianney" },
  { text: "El que se excusa, se acusa.", author: "San Jerónimo" },
  { text: "La fe es creer lo que no vemos, y la recompensa es ver lo que creemos.", author: "San Agustín" },
  { text: "No hay nada en esta tierra más preciado que la verdadera amistad.", author: "Santo Tomás de Aquino" },
  { text: "Un amigo fiel es un refugio seguro.", author: "Eclesiástico 6, 14" },
  { text: "El Señor es mi roca, mi fortaleza y mi libertador.", author: "Salmo 18, 2" },
  { text: "Crea en mí, oh Dios, un corazón puro, y renueva un espíritu recto dentro de mí.", author: "Salmo 51, 10" },
  { text: "Pon tu delicia en el Señor, y él te concederá los anhelos de tu corazón.", author: "Salmo 37, 4" },
  { text: "El amor de Dios es el ala que nos eleva al cielo.", author: "San Miguel Ángel" },
  { text: "La vida es un don, y nos la dieron para que la diéramos.", author: "San Juan Pablo II" },
  { text: "La Eucaristía es el corazón palpitante de la Iglesia.", author: "Benedicto XVI" },
  { text: "La oración es el oxígeno del alma.", author: "San Pío de Pietrelcina" },
  { text: "La fe y la razón son como las dos alas con las cuales el espíritu humano se eleva hacia la contemplación de la verdad.", author: "San Juan Pablo II" },
  { text: "La vida es belleza, admírala.", author: "Santa Teresa de Calcuta" },
  { text: "La caridad es la sonrisa de Dios.", author: "San Vicente de Paúl" },
  { text: "El que confía en sí mismo es un necio, pero el que anda con sabiduría está seguro.", author: "Proverbios 28, 26" },
  { text: "La verdadera conversión consiste en volverse a Dios con todo el corazón.", author: "San Bernardo de Claraval" },
  { text: "La Eucaristía es el sacramento del amor.", author: "Santo Tomás de Aquino" },
  { text: "Porque para mí el vivir es Cristo, y el morir es ganancia.", author: "Filipenses 1, 21" },
  { text: "La alegría que debes tener no es esa que podríamos llamar fisiológica, de animal sano, sino otra sobrenatural.", author: "San Josemaría Escrivá" },
  { text: "Si alguno dice: «Amo a Dios», y aborrece a su hermano, es un mentiroso.", author: "1 Juan 4, 20" },
  { text: "No pases indiferente ante el dolor ajeno. Esa persona... es tu hermano.", author: "San Josemaría Escrivá" },
  { text: "La alegría es consecuencia necesaria de la filiación divina, de sabernos queridos entrañablemente por nuestro Padre-Dios.", author: "San Josemaría Escrivá" },
  { text: "Me has hecho, Señor, para Ti, y mi corazón está inquieto hasta que descanse en Ti.", author: "San Agustín" },
  { text: "La oración es un diálogo con Dios en el que el alma expresa sus sentimientos.", author: "San Francisco de Sales" },
  { text: "El Rosario es la cadena dulce que nos une con el cielo.", author: "San Pío de Pietrelcina" },
  { text: "La humildad atrae la gracia de Dios como el imán atrae el hierro.", author: "San Vicente Ferrer" },
  { text: "El que mucho ama, mucho perdona.", author: "Lc 7, 47" },
  { text: "La caridad no es una virtud entre otras, sino el corazón de todas las virtudes.", author: "San Bernardo de Claraval" },
  { text: "El alma enamorada de Dios es una viña fecunda.", author: "San Juan de la Cruz" },
  { text: "No hay paz sin justicia, no hay justicia sin perdón.", author: "San Juan Pablo II" },
  { text: "La vida es un don para amar, para alabar y para servir.", author: "San Juan Pablo II" },
  { text: "La santidad es la plenitud de la vida cristiana.", author: "Benedicto XVI" },
  { text: "El que no conoce a Jesús no conoce a Dios.", author: "San Ireneo de Lyon" },
  { text: "La fe es el fundamento de toda justicia.", author: "San Clemente de Roma" },
  { text: "La oración es la fortaleza del hombre y la debilidad de Dios.", author: "San Agustín" },
  { text: "La esperanza cristiana no es un optimismo vacío, sino la certeza de que Dios nos ama.", author: "Benedicto XVI" },
  { text: "La verdadera pobreza consiste en no tener nada y no desear nada.", author: "San Francisco de Asís" },
  { text: "La caridad es la medida con la que seremos medidos en el juicio final.", author: "San Juan de la Cruz" },
  { text: "La Eucaristía es el tesoro más grande de la Iglesia.", author: "San Cirilo de Jerusalén" },
  { text: "El que se pierde por amor, se encuentra en Dios.", author: "San Agustín" },
  { text: "El silencio es el pórtico de la oración.", author: "Santa Teresa de Jesús" },
  { text: "La cruz no es para llevarla, sino para abrazarla.", author: "San Francisco de Sales" },
  { text: "El que quiera ser el primero, que sea el último de todos y el servidor de todos.", author: "Mc 9, 35" },
  { text: "No os conforméis a este mundo, sino transformaos por medio de la renovación de vuestro entendimiento.", author: "Romanos 12, 2" },
  { text: "Revestíos de la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo.", author: "Efesios 6, 11" },
  { text: "La oración del justo, obrando eficazmente, puede mucho.", author: "Santiago 5, 16" },
  { text: "Todo lo que pidáis en la oración, creyendo, lo recibiréis.", author: "Mt 21, 22" },
  { text: "El que no renuncia a todo lo que posee, no puede ser mi discípulo.", author: "Lc 14, 33" },
  { text: "El que me sigue no andará en tinieblas, sino que tendrá la luz de la vida.", author: "Jn 8, 12" },
  { text: "El que permanece en el amor, permanece en Dios, y Dios en él.", author: "1 Juan 4, 16" },
  { text: "El amor de Dios es el principio y el fin de todas las cosas.", author: "Santo Tomás de Aquino" },
  { text: "La humildad es la madre de todas las virtudes.", author: "San Bernardo de Claraval" },
  { text: "La oración es el pan del alma.", author: "San Agustín" },
  { text: "La caridad es el sol que ilumina todas las virtudes.", author: "San Francisco de Sales" },
  { text: "La fe es el ojo del alma.", author: "San Efrén de Siria" },
  { text: "La esperanza es el ancla del alma.", author: "San Juan Crisóstomo" },
  { text: "La paciencia es la fortaleza de los débiles y la debilidad de los fuertes.", author: "San Bernardo de Claraval" },
  { text: "La obediencia es la muerte de la voluntad propia y la vida de la virtud.", author: "San Francisco de Sales" },
  { text: "La pobreza de espíritu es el tesoro más grande del cristiano.", author: "San Lorenzo de Brindisi" },
  { text: "La castidad es la flor de la vida espiritual.", author: "San Felipe Neri" },
  { text: "La perseverancia es la victoria de los santos.", author: "San Agustín" },
  { text: "La alegría es la señal de que el alma está con Dios.", author: "San Juan Bosco" },
  { text: "La santidad es la unión con Dios.", author: "Santa Teresa de los Andes" },
  { text: "La oración es el elevador del alma al cielo.", author: "San Juan Clímaco" },
  { text: "La Eucaristía es el anticipo del cielo en la tierra.", author: "San Juan Pablo II" },
  { text: "La Virgen María es el camino más corto, más seguro y más perfecto para llegar a Jesús.", author: "San Luis María Grignion de Montfort" },
  { text: "El Espíritu Santo es el alma de la Iglesia.", author: "León XIII" },
  { text: "La Iglesia es la barca de Pedro que nunca se hundirá.", author: "San Ambrosio" },
  { text: "La Biblia es la carta de amor de Dios a la humanidad.", author: "San Gregorio Magno" },
  { text: "Los sacramentos son los canales de la gracia de Dios.", author: "Santo Tomás de Aquino" },
  { text: "La cruz es la llave del paraíso.", author: "San Agustín" },
  { text: "El sufrimiento es la moneda con la que se compra el cielo.", author: "Santa Rosa de Lima" },
  { text: "La muerte es el comienzo de la verdadera vida.", author: "Santa Teresa de Lisieux" },
  { text: "El cielo es la patria de los que aman a Dios.", author: "San Juan Bosco" },
  { text: "El infierno es la ausencia de Dios.", author: "San Juan de la Cruz" },
  { text: "El purgatorio es el lugar de la purificación del amor.", author: "Santa Catalina de Génova" },
  { text: "Los ángeles son nuestros protectores y guías.", author: "San Bernardo de Claraval" },
  { text: "Los santos son nuestros intercesores y modelos.", author: "San Alfonso María de Ligorio" },
  { text: "El diablo es el padre de la mentira y el homicida desde el principio.", author: "Jn 8, 44" },
  { text: "El pecado es la ofensa a Dios y la herida del alma.", author: "San Agustín" },
  { text: "La gracia es el don de Dios que nos hace capaces de amarlo y servirlo.", author: "Catecismo de la Iglesia Católica" },
  { text: "La virtud es el hábito de hacer el bien.", author: "Aristóteles" },
  { text: "La felicidad es la posesión de Dios.", author: "San Agustín" },
  { text: "La paz es la tranquilidad del orden.", author: "San Agustín" },
  { text: "La justicia es dar a cada uno lo que le corresponde.", author: "Ulpiano" },
  { text: "La misericordia es la justicia de Dios.", author: "San Juan Pablo II" },
  { text: "La vida es un don de Dios que debemos custodiar y respetar.", author: "San Juan Pablo II" },
  { text: "La familia es el santuario de la vida y el amor.", author: "San Juan Pablo II" },
  { text: "El trabajo es un medio de santificación y de servicio a los demás.", author: "San Josemaría Escrivá" },
  { text: "La política es la forma más alta de la caridad.", author: "Pío XI" },
  { text: "La ciencia y la fe no se oponen, sino que se complementan.", author: "San Juan Pablo II" },
  { text: "El arte es un reflejo de la belleza de Dios.", author: "San Juan Pablo II" },
  { text: "La historia es la maestra de la vida.", author: "Cicerón" },
  { text: "El ecumenismo es el camino hacia la unidad de los cristianos.", author: "Concilio Vaticano II" },
  { text: "El diálogo interreligioso es el camino hacia la paz y la concordia entre los pueblos.", author: "San Juan Pablo II" },
  { text: "La nueva evangelización es el anuncio de Cristo con nuevo ardor, nuevos métodos y nuevas expresiones.", author: "San Juan Pablo II" },
  { text: "La misión ad gentes es el deber de todo cristiano de anunciar el Evangelio a los que no lo conocen.", author: "San Juan Pablo II" },
  { text: "La santidad es la vocación de todo cristiano.", author: "Concilio Vaticano II" },
  { text: "La santidad es la perfección de la caridad.", author: "Santo Tomás de Aquino" },
  { text: "La santidad es la obra de la gracia de Dios en nosotros.", author: "San Agustín" },
  { text: "La santidad es el fruto del Espíritu Santo.", author: "Gálatas 5, 22-23" },
  { text: "La santidad es el camino de la felicidad.", author: "San Juan Bosco" },
  { text: "La santidad es el amor a Dios y al prójimo.", author: "Mt 22, 37-39" },
  { text: "La santidad es la imitación de Cristo.", author: "1 Pedro 2, 21" },
  { text: "La santidad es la participación en la vida de Dios.", author: "2 Pedro 1, 4" },
  { text: "La santidad es la gloria de Dios.", author: "San Ireneo de Lyon" },
  { text: "La santidad es el fin del hombre.", author: "San Agustín" },
  { text: "El que quiera seguirme, que se niegue a sí mismo, tome su cruz y me siga.", author: "Mt 16, 24" },
  { text: "El que ama a su padre o a su madre más que a mí, no es digno de mí.", author: "Mt 10, 37" },
  { text: "El que no toma su cruz y me sigue, no es digno de mí.", author: "Mt 10, 38" },
  { text: "El que encuentre su vida, la perderá; y el que pierda su vida por mí, la encontrará.", author: "Mt 10, 39" },
  { text: "El que os recibe a vosotros, a mí me recibe; y el que me recibe a mí, recibe al que me ha enviado.", author: "Mt 10, 40" },
  { text: "El que dé a beber un solo vaso de agua fresca a uno de estos pequeños por ser mi discípulo, en verdad os digo que no perderá su recompensa.", author: "Mt 10, 42" },
  { text: "El que siembra escasamente, escasamente cosechará; el que siembra generosamente, generosamente cosechará.", author: "2 Corintios 9, 6" },
  { text: "Dios ama al que da con alegría.", author: "2 Corintios 9, 7" },
  { text: "Bástale a cada día su propio afán.", author: "Mt 6, 34" },
  { text: "No acumuléis tesoros en la tierra, donde la polilla y el orín los corroen.", author: "Mt 6, 19" },
  { text: "Buscad las cosas de arriba, no las de la tierra.", author: "Colosenses 3, 1-2" },
  { text: "No améis al mundo ni lo que hay en el mundo. Si alguno ama al mundo, el amor del Padre no está en él.", author: "1 Juan 2, 15" },
  { text: "El mundo pasa, y sus deseos; pero el que hace la voluntad de Dios permanece para siempre.", author: "1 Juan 2, 17" },
  { text: "No tenemos aquí ciudad permanente, sino que buscamos la futura.", author: "Hebreos 13, 14" },
  { text: "Nuestra ciudadanía está en los cielos.", author: "Filipenses 3, 20" },
  { text: "Aspirad a los bienes de arriba, no a los de la tierra.", author: "Colosenses 3, 2" },
  { text: "Todo es vuestro, pero vosotros sois de Cristo, y Cristo es de Dios.", author: "1 Corintios 3, 22-23" },
  { text: "El que se gloría, gloríese en el Señor.", author: "1 Corintios 1, 31" },
  { text: "No a nosotros, Señor, no a nosotros, sino a tu nombre da la gloria.", author: "Salmo 115, 1" },
  { text: "El que se alaba a sí mismo no es aprobado, sino aquel a quien el Señor alaba.", author: "2 Corintios 10, 18" },
  { text: "El que se cree algo, no siendo nada, a sí mismo se engaña.", author: "Gálatas 6, 3" },
  { text: "Dios resiste a los soberbios y da su gracia a los humildes.", author: "Santiago 4, 6" },
  { text: "Humillaos bajo la poderosa mano de Dios, para que él os exalte a su tiempo.", author: "1 Pedro 5, 6" },
  { text: "Aprended de mí, que soy manso y humilde de corazón.", author: "Mt 11, 29" },
  { text: "El que es mayor entre vosotros será vuestro servidor.", author: "Mt 23, 11" },
  { text: "El que se humilla será enaltecido.", author: "Lc 14, 11" },
  { text: "El que no vive para servir, no sirve para vivir.", author: "San Juan Pablo II" },
  { text: "No tengas miedo de la santidad; Dios te llama a ella aquí y ahora.", author: "San Josemaría"},
  { text: "La santidad consiste en vivir con amor las cosas pequeñas.", author: "San Josemaría"},
  { text: "No tengáis miedo de abrir las puertas a Cristo.", author: "San Juan Pablo II"},
  { text: "La libertad verdadera se encuentra en la obediencia al bien.", author: "San Juan Pablo II"},
  { text: "Cada hombre debe encontrar su camino hacia la verdad con la luz de su conciencia.", author: "San Juan Pablo II"},
  { text: "La fe y la razón son como dos alas con las que el espíritu humano se eleva hacia la verdad.", author: "San Juan Pablo II"},
  { text: "La alegría del Evangelio llena el corazón y la vida entera de los que se encuentran con Jesús.", author: "Papa Francisco"},
  { text: "La misericordia es la fuerza que cambia el mundo.", author: "Papa Francisco"},
  { text: "No podemos quedarnos indiferentes ante el sufrimiento de los demás.", author: "Papa Francisco"},
  { text: "Ser cristiano no es solo seguir reglas, es dejarse transformar por el amor de Dios.", author: "Papa Francisco"},
  { text: "La santa pureza la da Dios cuando se pide con humildad.", author: "San Josemaría"},
  { text: "Si alguno quiere venir en pos de mí, tome su cruz de cada día y sígame.", author: "Mt 16, 24"},
  { text: "Una fe sin cuestionar, es una fe sin fundamento.", author: "Anónimo"},
  { text: "¡No tengáis miedo de mirarlo a Él! ¡Mirad al Señor!", author: "San Juan Pablo II"},
  { text: "El que canta, reza dos veces.", author: "San Agustín"},
  { text: "Una fe sin ser precedida por la duda, es como unos cimientos en la arena: se desmonorará ante la dificultad y perecerá", author: "Anónimo"},
  { text: "Dame tu amor y tu gracia, que eso me basta", author: "San Ignacio de Loyola"}
];