import { additionalSpiritualTriviaQuestions } from '@/lib/trivia-questions-extra';

export type TriviaCategoryId = 'jesus' | 'antiguo-testamento' | 'santos' | 'san-josemaria';
export type TriviaDifficultyId = 'inicial' | 'intermedia' | 'avanzada';

export interface TriviaCategory {
  id: TriviaCategoryId;
  label: string;
  description: string;
}

export interface TriviaQuestionDefinition {
  id: string;
  category: TriviaCategoryId;
  prompt: string;
  options: readonly [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
  explanation: string;
  source: string;
}

export interface TriviaQuestion extends TriviaQuestionDefinition {
  difficulty: TriviaDifficultyId;
}

export interface TriviaDifficulty {
  id: TriviaDifficultyId;
  label: string;
  description: string;
}

export const triviaCategories: readonly TriviaCategory[] = [
  {
    id: 'jesus',
    label: 'Vida de Jesús',
    description: 'Evangelio, parábolas, signos, Pasión y Resurrección.',
  },
  {
    id: 'antiguo-testamento',
    label: 'Antiguo Testamento',
    description: 'Patriarcas, éxodo, reyes, profetas y libros históricos.',
  },
  {
    id: 'santos',
    label: 'Santos',
    description: 'Vidas y enseñanzas de testigos destacados de la Iglesia.',
  },
  {
    id: 'san-josemaria',
    label: 'San Josemaría',
    description: 'Vida, mensaje, fundación y obras escritas.',
  },
] as const;

export const triviaDifficulties: readonly TriviaDifficulty[] = [
  {
    id: 'inicial',
    label: 'Inicial',
    description: 'Hechos centrales y referencias ampliamente conocidas.',
  },
  {
    id: 'intermedia',
    label: 'Intermedia',
    description: 'Detalles que requieren una lectura más atenta o conocimiento previo.',
  },
  {
    id: 'avanzada',
    label: 'Avanzada',
    description: 'Personajes, textos y datos específicos para profundizar.',
  },
] as const;

const originalSpiritualTriviaQuestions: readonly TriviaQuestionDefinition[] = [
  {
    id: 'jesus-01',
    category: 'jesus',
    prompt: '¿En qué localidad nació Jesús?',
    options: ['Nazaret', 'Belén', 'Jerusalén', 'Cafarnaúm'],
    correctIndex: 1,
    explanation: 'José y María fueron a Belén por el censo, y allí nació Jesús.',
    source: 'Lc 2,1-7',
  },
  {
    id: 'jesus-02',
    category: 'jesus',
    prompt: '¿Qué respondió María al anuncio del ángel Gabriel?',
    options: [
      'Que necesitaba una señal',
      'Que consultaría a Isabel',
      'Hágase en mí según tu palabra',
      'Que volvería a Nazaret',
    ],
    correctIndex: 2,
    explanation: 'María acogió libremente la voluntad de Dios con su fiat.',
    source: 'Lc 1,26-38',
  },
  {
    id: 'jesus-03',
    category: 'jesus',
    prompt: '¿Quién fue el padre legal y custodio de Jesús?',
    options: ['Zacarías', 'José', 'Simeón', 'Joaquín'],
    correctIndex: 1,
    explanation: 'José, esposo de María, recibió a Jesús y cuidó de la Sagrada Familia.',
    source: 'Mt 1,18-25',
  },
  {
    id: 'jesus-04',
    category: 'jesus',
    prompt: '¿Quién bautizó a Jesús en el río Jordán?',
    options: ['Pedro', 'Juan el Bautista', 'Andrés', 'Zacarías'],
    correctIndex: 1,
    explanation: 'Jesús acudió a Juan el Bautista y, al salir del agua, se manifestó la Trinidad.',
    source: 'Mt 3,13-17',
  },
  {
    id: 'jesus-05',
    category: 'jesus',
    prompt: '¿Cuánto duró el ayuno de Jesús en el desierto?',
    options: ['Siete días', 'Doce días', 'Treinta días', 'Cuarenta días y cuarenta noches'],
    correctIndex: 3,
    explanation: 'Antes de comenzar su ministerio público, Jesús ayunó cuarenta días y fue tentado.',
    source: 'Mt 4,1-11',
  },
  {
    id: 'jesus-06',
    category: 'jesus',
    prompt: '¿Cuál es el primer signo de Jesús narrado por san Juan?',
    options: [
      'La multiplicación de los panes',
      'La curación del ciego de nacimiento',
      'El agua convertida en vino en Caná',
      'La resurrección de Lázaro',
    ],
    correctIndex: 2,
    explanation: 'En las bodas de Caná, Jesús convirtió el agua en vino y manifestó su gloria.',
    source: 'Jn 2,1-11',
  },
  {
    id: 'jesus-07',
    category: 'jesus',
    prompt: '¿Qué oficio tenían Pedro y Andrés cuando Jesús los llamó?',
    options: ['Carpinteros', 'Pescadores', 'Publicanos', 'Pastores'],
    correctIndex: 1,
    explanation: 'Echaban las redes en el mar de Galilea; Jesús los llamó a ser pescadores de hombres.',
    source: 'Mt 4,18-20',
  },
  {
    id: 'jesus-08',
    category: 'jesus',
    prompt: '¿Con qué enseñanza comienza el Sermón de la Montaña?',
    options: ['Las bienaventuranzas', 'El juicio final', 'El buen samaritano', 'El hijo pródigo'],
    correctIndex: 0,
    explanation: 'Jesús proclama bienaventurados a los pobres de espíritu, mansos, misericordiosos y demás.',
    source: 'Mt 5,1-12',
  },
  {
    id: 'jesus-09',
    category: 'jesus',
    prompt: '¿Qué oración enseñó Jesús a sus discípulos?',
    options: ['El Magníficat', 'El Benedictus', 'El Padre nuestro', 'El Gloria'],
    correctIndex: 2,
    explanation: 'Jesús enseñó a dirigirse a Dios como Padre y a pedir su Reino, el pan y el perdón.',
    source: 'Mt 6,9-13; Lc 11,1-4',
  },
  {
    id: 'jesus-10',
    category: 'jesus',
    prompt: '¿Dónde construye su casa el hombre prudente de la parábola?',
    options: ['Sobre arena', 'Junto al camino', 'Sobre roca', 'En tierra fértil'],
    correctIndex: 2,
    explanation: 'Quien escucha y cumple las palabras de Jesús se parece al que edifica sobre roca.',
    source: 'Mt 7,24-27',
  },
  {
    id: 'jesus-11',
    category: 'jesus',
    prompt: '¿A qué se subió Zaqueo para poder ver a Jesús?',
    options: ['A una palmera', 'A una higuera', 'A un sicómoro', 'A una muralla'],
    correctIndex: 2,
    explanation: 'Zaqueo, de baja estatura, subió a un sicómoro; Jesús después se hospedó en su casa.',
    source: 'Lc 19,1-10',
  },
  {
    id: 'jesus-12',
    category: 'jesus',
    prompt: '¿Cómo se llamaba el amigo de Jesús que fue resucitado en Betania?',
    options: ['Jairo', 'Lázaro', 'Bartimeo', 'Nicodemo'],
    correctIndex: 1,
    explanation: 'Jesús llamó a Lázaro fuera del sepulcro después de cuatro días.',
    source: 'Jn 11,1-44',
  },
  {
    id: 'jesus-13',
    category: 'jesus',
    prompt: '¿Cuántos panes y peces había antes de alimentar a la multitud, según san Juan?',
    options: ['Cinco panes y dos peces', 'Siete panes y tres peces', 'Doce panes y un pez', 'Dos panes y cinco peces'],
    correctIndex: 0,
    explanation: 'Un muchacho ofreció cinco panes de cebada y dos peces, que Jesús multiplicó.',
    source: 'Jn 6,1-13',
  },
  {
    id: 'jesus-14',
    category: 'jesus',
    prompt: '¿Qué hizo Jesús para calmar la tempestad en el lago?',
    options: ['Mandó al viento y al mar que callaran', 'Pidió a Pedro remar', 'Abandonó la barca', 'Esperó hasta el amanecer'],
    correctIndex: 0,
    explanation: 'Jesús increpó al viento y al mar, y sobrevino una gran calma.',
    source: 'Mc 4,35-41',
  },
  {
    id: 'jesus-15',
    category: 'jesus',
    prompt: '¿Qué tres apóstoles acompañaron a Jesús en la Transfiguración?',
    options: ['Pedro, Andrés y Mateo', 'Pedro, Santiago y Juan', 'Felipe, Tomás y Bartolomé', 'Santiago, Judas y Simón'],
    correctIndex: 1,
    explanation: 'Pedro, Santiago y Juan vieron a Jesús transfigurado y oyeron la voz del Padre.',
    source: 'Mt 17,1-8',
  },
  {
    id: 'jesus-16',
    category: 'jesus',
    prompt: '¿Quiénes aparecieron hablando con Jesús durante la Transfiguración?',
    options: ['Abraham y David', 'Isaías y Jeremías', 'Moisés y Elías', 'Adán y Noé'],
    correctIndex: 2,
    explanation: 'Moisés y Elías representan la Ley y los Profetas, cumplidos en Cristo.',
    source: 'Mt 17,3',
  },
  {
    id: 'jesus-17',
    category: 'jesus',
    prompt: 'En la parábola, ¿quién atendió al hombre herido junto al camino?',
    options: ['Un sacerdote', 'Un levita', 'Un samaritano', 'Un soldado'],
    correctIndex: 2,
    explanation: 'El samaritano se compadeció, curó sus heridas y se hizo prójimo del necesitado.',
    source: 'Lc 10,25-37',
  },
  {
    id: 'jesus-18',
    category: 'jesus',
    prompt: '¿Qué hizo el padre cuando regresó el hijo pródigo?',
    options: ['Lo recibió con misericordia y celebró', 'Lo hizo esperar fuera', 'Le exigió devolver el dinero', 'Lo envió con su hermano'],
    correctIndex: 0,
    explanation: 'El padre corrió a abrazarlo, lo restituyó como hijo y preparó una fiesta.',
    source: 'Lc 15,11-32',
  },
  {
    id: 'jesus-19',
    category: 'jesus',
    prompt: '¿Qué confesó Pedro en Cesarea de Filipo?',
    options: ['Tú eres Elías', 'Tú eres el Cristo, el Hijo de Dios vivo', 'Tú eres Juan el Bautista', 'Tú eres uno de los profetas'],
    correctIndex: 1,
    explanation: 'Pedro reconoció en Jesús al Mesías y al Hijo de Dios vivo.',
    source: 'Mt 16,13-20',
  },
  {
    id: 'jesus-20',
    category: 'jesus',
    prompt: '¿Sobre qué animal entró Jesús en Jerusalén?',
    options: ['Un caballo', 'Un camello', 'Un asno', 'Una mula real'],
    correctIndex: 2,
    explanation: 'Jesús entró humilde, montado en un asno, cumpliendo la profecía de Zacarías.',
    source: 'Mt 21,1-11; Zac 9,9',
  },
  {
    id: 'jesus-21',
    category: 'jesus',
    prompt: '¿Qué sacramento instituyó Jesús con el pan y el vino en la Última Cena?',
    options: ['El Bautismo', 'La Confirmación', 'La Eucaristía', 'La Unción de los enfermos'],
    correctIndex: 2,
    explanation: 'Jesús entregó su Cuerpo y su Sangre y mandó hacer esto en memoria suya.',
    source: 'Lc 22,14-20; 1 Co 11,23-26',
  },
  {
    id: 'jesus-22',
    category: 'jesus',
    prompt: '¿En qué huerto oró Jesús antes de ser arrestado?',
    options: ['Getsemaní', 'Edén', 'Siloé', 'Betesda'],
    correctIndex: 0,
    explanation: 'En Getsemaní, Jesús aceptó la voluntad del Padre en medio de la angustia.',
    source: 'Mt 26,36-46',
  },
  {
    id: 'jesus-23',
    category: 'jesus',
    prompt: '¿Con qué señal entregó Judas a Jesús?',
    options: ['Con una moneda', 'Con un beso', 'Con una antorcha', 'Con una acusación escrita'],
    correctIndex: 1,
    explanation: 'Judas había acordado señalar con un beso a aquel que debían prender.',
    source: 'Mt 26,47-50',
  },
  {
    id: 'jesus-24',
    category: 'jesus',
    prompt: '¿Quién encontró el sepulcro vacío y luego reconoció a Jesús resucitado en el jardín?',
    options: ['Marta', 'María Magdalena', 'Salomé', 'Juana'],
    correctIndex: 1,
    explanation: 'María Magdalena reconoció al Señor cuando Él la llamó por su nombre.',
    source: 'Jn 20,1-18',
  },
  {
    id: 'jesus-25',
    category: 'jesus',
    prompt: '¿Qué misión dio Jesús resucitado a los Once al final del Evangelio de Mateo?',
    options: ['Volver a sus antiguos oficios', 'Enseñar solo en Jerusalén', 'Hacer discípulos a todos los pueblos', 'Esperar ocultos indefinidamente'],
    correctIndex: 2,
    explanation: 'Jesús los envió a todas las naciones para bautizar y enseñar cuanto Él había mandado.',
    source: 'Mt 28,16-20',
  },

  {
    id: 'antiguo-testamento-01',
    category: 'antiguo-testamento',
    prompt: '¿Qué creó Dios en el primer día, según el Génesis?',
    options: ['Los astros', 'La luz', 'Los animales', 'El ser humano'],
    correctIndex: 1,
    explanation: 'Dios dijo «Hágase la luz» y separó la luz de las tinieblas.',
    source: 'Gn 1,1-5',
  },
  {
    id: 'antiguo-testamento-02',
    category: 'antiguo-testamento',
    prompt: '¿Cuál fue la señal de la alianza de Dios con Noé?',
    options: ['La zarza ardiente', 'El arco iris', 'Las tablas de piedra', 'Una estrella'],
    correctIndex: 1,
    explanation: 'Dios puso el arco en las nubes como signo de su alianza con la tierra.',
    source: 'Gn 9,8-17',
  },
  {
    id: 'antiguo-testamento-03',
    category: 'antiguo-testamento',
    prompt: '¿Qué nuevo nombre recibió Abram?',
    options: ['Israel', 'Abraham', 'Isaac', 'Efraín'],
    correctIndex: 1,
    explanation: 'Dios lo llamó Abraham porque sería padre de una multitud de naciones.',
    source: 'Gn 17,1-8',
  },
  {
    id: 'antiguo-testamento-04',
    category: 'antiguo-testamento',
    prompt: '¿Cómo se llamó el hijo de Abraham y Sara?',
    options: ['Ismael', 'Jacob', 'Isaac', 'José'],
    correctIndex: 2,
    explanation: 'Isaac fue el hijo de la promesa, nacido cuando sus padres eran ancianos.',
    source: 'Gn 21,1-7',
  },
  {
    id: 'antiguo-testamento-05',
    category: 'antiguo-testamento',
    prompt: '¿Qué nombre recibió Jacob después de luchar durante la noche?',
    options: ['Judá', 'Israel', 'Benjamín', 'Moisés'],
    correctIndex: 1,
    explanation: 'Jacob recibió el nombre Israel; de sus hijos proceden las tribus de Israel.',
    source: 'Gn 32,23-33',
  },
  {
    id: 'antiguo-testamento-06',
    category: 'antiguo-testamento',
    prompt: '¿Por qué llegó José, hijo de Jacob, a Egipto?',
    options: ['Fue enviado como embajador', 'Sus hermanos lo vendieron', 'Huyó de una guerra', 'Buscaba a Moisés'],
    correctIndex: 1,
    explanation: 'Movidos por la envidia, sus hermanos lo vendieron; Dios convirtió aquel mal en salvación.',
    source: 'Gn 37,12-36; 50,20',
  },
  {
    id: 'antiguo-testamento-07',
    category: 'antiguo-testamento',
    prompt: '¿Desde dónde llamó Dios a Moisés en el desierto?',
    options: ['Desde una nube oscura', 'Desde una zarza que ardía sin consumirse', 'Desde el río Nilo', 'Desde una cueva'],
    correctIndex: 1,
    explanation: 'Dios se manifestó en la zarza ardiente y envió a Moisés a liberar a su pueblo.',
    source: 'Ex 3,1-12',
  },
  {
    id: 'antiguo-testamento-08',
    category: 'antiguo-testamento',
    prompt: '¿Qué debían poner los israelitas en los dinteles durante la primera Pascua?',
    options: ['Aceite', 'Agua', 'Sangre del cordero', 'Harina'],
    correctIndex: 2,
    explanation: 'La sangre del cordero fue señal para que el exterminador pasara de largo.',
    source: 'Ex 12,1-14',
  },
  {
    id: 'antiguo-testamento-09',
    category: 'antiguo-testamento',
    prompt: '¿Qué mar atravesó Israel al salir de Egipto?',
    options: ['Mar Muerto', 'Mar Rojo', 'Mar Mediterráneo', 'Mar de Galilea'],
    correctIndex: 1,
    explanation: 'Dios abrió las aguas del mar para que el pueblo cruzara por tierra seca.',
    source: 'Ex 14,15-31',
  },
  {
    id: 'antiguo-testamento-10',
    category: 'antiguo-testamento',
    prompt: '¿En qué monte recibió Moisés los mandamientos?',
    options: ['Carmelo', 'Tabor', 'Sinaí', 'Sión'],
    correctIndex: 2,
    explanation: 'En el Sinaí, Dios selló la alianza y entregó las palabras de la Ley.',
    source: 'Ex 19,1-20,21',
  },
  {
    id: 'antiguo-testamento-11',
    category: 'antiguo-testamento',
    prompt: '¿Qué alimento encontró Israel cada mañana en el desierto?',
    options: ['Miel', 'Maná', 'Uvas', 'Lentejas'],
    correctIndex: 1,
    explanation: 'Dios dio el maná, el pan del cielo, para alimentar al pueblo durante su marcha.',
    source: 'Ex 16,4-18',
  },
  {
    id: 'antiguo-testamento-12',
    category: 'antiguo-testamento',
    prompt: '¿Quién sucedió a Moisés y condujo al pueblo a la tierra prometida?',
    options: ['Aarón', 'Caleb', 'Josué', 'Gedeón'],
    correctIndex: 2,
    explanation: 'Josué recibió la misión de cruzar el Jordán y conducir a Israel.',
    source: 'Jos 1,1-9',
  },
  {
    id: 'antiguo-testamento-13',
    category: 'antiguo-testamento',
    prompt: '¿Qué ciudad vio caer sus murallas después de que Israel marchara a su alrededor?',
    options: ['Jericó', 'Nínive', 'Babilonia', 'Hebrón'],
    correctIndex: 0,
    explanation: 'Tras siete días y el sonido de las trompetas, cayeron las murallas de Jericó.',
    source: 'Jos 6,1-20',
  },
  {
    id: 'antiguo-testamento-14',
    category: 'antiguo-testamento',
    prompt: '¿A quién prometió Rut: «Tu pueblo será mi pueblo y tu Dios será mi Dios»?',
    options: ['A Ester', 'A Noemí', 'A Débora', 'A Ana'],
    correctIndex: 1,
    explanation: 'Rut permaneció fiel a su suegra Noemí y pasó a formar parte del pueblo de la alianza.',
    source: 'Rt 1,15-18',
  },
  {
    id: 'antiguo-testamento-15',
    category: 'antiguo-testamento',
    prompt: '¿Qué respondió Samuel cuando comprendió que Dios lo llamaba?',
    options: ['Aquí estoy, envíame', 'Habla, Señor, que tu siervo escucha', 'Señor, aumenta mi fe', 'Hágase tu voluntad'],
    correctIndex: 1,
    explanation: 'Guiado por Elí, Samuel aprendió a escuchar y responder a la llamada de Dios.',
    source: '1 S 3,1-10',
  },
  {
    id: 'antiguo-testamento-16',
    category: 'antiguo-testamento',
    prompt: '¿Quién fue el primer rey de Israel?',
    options: ['David', 'Salomón', 'Saúl', 'Samuel'],
    correctIndex: 2,
    explanation: 'Samuel ungió a Saúl como primer rey; después David fue escogido para sucederlo.',
    source: '1 S 9,15-10,1',
  },
  {
    id: 'antiguo-testamento-17',
    category: 'antiguo-testamento',
    prompt: '¿Con qué arma derribó David a Goliat?',
    options: ['Una espada', 'Una lanza', 'Una honda y una piedra', 'Un arco'],
    correctIndex: 2,
    explanation: 'David confió en el Señor y venció al filisteo con una piedra lanzada con su honda.',
    source: '1 S 17,38-51',
  },
  {
    id: 'antiguo-testamento-18',
    category: 'antiguo-testamento',
    prompt: '¿Qué pidió Salomón a Dios al comenzar su reinado?',
    options: ['Riquezas', 'Larga vida', 'Un corazón sabio para gobernar', 'La derrota de todos sus enemigos'],
    correctIndex: 2,
    explanation: 'Salomón pidió discernimiento para gobernar con justicia, y su petición agradó a Dios.',
    source: '1 R 3,4-15',
  },
  {
    id: 'antiguo-testamento-19',
    category: 'antiguo-testamento',
    prompt: '¿Qué profeta desafió a los profetas de Baal en el monte Carmelo?',
    options: ['Isaías', 'Elías', 'Eliseo', 'Jeremías'],
    correctIndex: 1,
    explanation: 'Elías oró y el fuego del Señor consumió el sacrificio, mostrando quién es el Dios verdadero.',
    source: '1 R 18,20-39',
  },
  {
    id: 'antiguo-testamento-20',
    category: 'antiguo-testamento',
    prompt: '¿En qué río se bañó Naamán para quedar limpio de la lepra?',
    options: ['Jordán', 'Nilo', 'Éufrates', 'Tigris'],
    correctIndex: 0,
    explanation: 'Eliseo le mandó bañarse siete veces en el Jordán; Naamán obedeció y quedó limpio.',
    source: '2 R 5,1-14',
  },
  {
    id: 'antiguo-testamento-21',
    category: 'antiguo-testamento',
    prompt: '¿Qué nombre anuncia Isaías para el niño que será señal de Dios con nosotros?',
    options: ['Emmanuel', 'Melquisedec', 'Samuel', 'Ezequiel'],
    correctIndex: 0,
    explanation: 'Emmanuel significa «Dios con nosotros» y la profecía es leída por la Iglesia a la luz de Cristo.',
    source: 'Is 7,14; Mt 1,22-23',
  },
  {
    id: 'antiguo-testamento-22',
    category: 'antiguo-testamento',
    prompt: '¿Qué prometió Dios por medio de Jeremías escribir en el corazón de su pueblo?',
    options: ['Una genealogía', 'Una nueva alianza y su Ley', 'El nombre de los reyes', 'El plano del templo'],
    correctIndex: 1,
    explanation: 'La nueva alianza no quedaría solo en tablas: la Ley sería puesta en el interior y escrita en el corazón.',
    source: 'Jr 31,31-34',
  },
  {
    id: 'antiguo-testamento-23',
    category: 'antiguo-testamento',
    prompt: '¿Qué visión recibió Ezequiel como signo de la restauración de Israel?',
    options: ['Una escalera al cielo', 'Un valle de huesos secos que recobran vida', 'Una ciudad de oro', 'Un arca sobre las aguas'],
    correctIndex: 1,
    explanation: 'El Espíritu hace revivir los huesos secos, imagen de la esperanza que Dios devuelve a su pueblo.',
    source: 'Ez 37,1-14',
  },
  {
    id: 'antiguo-testamento-24',
    category: 'antiguo-testamento',
    prompt: '¿Por qué fue arrojado Daniel al foso de los leones?',
    options: ['Por negarse a dejar de orar a Dios', 'Por interpretar un sueño', 'Por huir de Babilonia', 'Por destruir una estatua'],
    correctIndex: 0,
    explanation: 'Daniel siguió orando fielmente pese al decreto; Dios cerró la boca de los leones.',
    source: 'Dn 6,7-24',
  },
  {
    id: 'antiguo-testamento-25',
    category: 'antiguo-testamento',
    prompt: '¿A qué ciudad fue enviado Jonás para predicar la conversión?',
    options: ['Tiro', 'Jerusalén', 'Nínive', 'Damasco'],
    correctIndex: 2,
    explanation: 'Jonás anunció el juicio en Nínive; sus habitantes hicieron penitencia y Dios tuvo misericordia.',
    source: 'Jon 3,1-10',
  },

  {
    id: 'santos-01',
    category: 'santos',
    prompt: '¿A qué apóstol dijo Jesús: «Te daré las llaves del Reino de los cielos»?',
    options: ['Juan', 'Pedro', 'Santiago', 'Andrés'],
    correctIndex: 1,
    explanation: 'Jesús confió a Pedro una misión particular de servicio y unidad en su Iglesia.',
    source: 'Mt 16,13-19',
  },
  {
    id: 'santos-02',
    category: 'santos',
    prompt: '¿Hacia qué ciudad iba san Pablo cuando se encontró con Cristo resucitado?',
    options: ['Roma', 'Antioquía', 'Damasco', 'Éfeso'],
    correctIndex: 2,
    explanation: 'Saulo iba a Damasco para perseguir cristianos cuando la luz de Cristo transformó su vida.',
    source: 'Hch 9,1-19',
  },
  {
    id: 'santos-03',
    category: 'santos',
    prompt: '¿Quién fue la madre de san Agustín y perseveró en rezar por su conversión?',
    options: ['Santa Mónica', 'Santa Escolástica', 'Santa Elena', 'Santa Macrina'],
    correctIndex: 0,
    explanation: 'Santa Mónica acompañó con oración y lágrimas el camino que llevó a Agustín a la fe.',
    source: 'Vatican News, Santos: santa Mónica',
  },
  {
    id: 'santos-04',
    category: 'santos',
    prompt: '¿De qué ciudad del norte de África fue obispo san Agustín?',
    options: ['Cartago', 'Hipona', 'Alejandría', 'Cirene'],
    correctIndex: 1,
    explanation: 'San Agustín fue obispo de Hipona y uno de los grandes Padres y doctores de la Iglesia.',
    source: 'Vatican News, Santos: san Agustín de Hipona',
  },
  {
    id: 'santos-05',
    category: 'santos',
    prompt: '¿Qué familia religiosa fundó san Benito de Nursia?',
    options: ['Los benedictinos', 'Los dominicos', 'Los jesuitas', 'Los cartujos'],
    correctIndex: 0,
    explanation: 'Su Regla organizó la vida monástica occidental en torno a la oración, el trabajo y la vida común.',
    source: 'Vatican News, Santos: san Benito de Nursia',
  },
  {
    id: 'santos-06',
    category: 'santos',
    prompt: '¿Con qué ciudad italiana se asocia especialmente san Francisco?',
    options: ['Padua', 'Asís', 'Milán', 'Rávena'],
    correctIndex: 1,
    explanation: 'Francisco nació en Asís y allí comenzó la fraternidad que viviría el Evangelio en pobreza.',
    source: 'Vatican News, Santos: san Francisco de Asís',
  },
  {
    id: 'santos-07',
    category: 'santos',
    prompt: '¿Qué comunidad femenina fundó santa Clara de Asís?',
    options: ['Las clarisas', 'Las ursulinas', 'Las salesas', 'Las visitandinas'],
    correctIndex: 0,
    explanation: 'Santa Clara siguió el ideal evangélico de Francisco y dio origen a las Hermanas Pobres, llamadas clarisas.',
    source: 'Vatican News, Santos: santa Clara de Asís',
  },
  {
    id: 'santos-08',
    category: 'santos',
    prompt: '¿Qué orden fundó santo Domingo de Guzmán?',
    options: ['Orden de los Hermanos Menores', 'Orden de Predicadores', 'Compañía de Jesús', 'Orden de la Merced'],
    correctIndex: 1,
    explanation: 'Los dominicos son la Orden de Predicadores, nacida para servir a la verdad mediante estudio y predicación.',
    source: 'Vatican News, Santos: santo Domingo de Guzmán',
  },
  {
    id: 'santos-09',
    category: 'santos',
    prompt: '¿A qué orden religiosa perteneció santo Tomás de Aquino?',
    options: ['Franciscanos', 'Dominicos', 'Benedictinos', 'Jesuitas'],
    correctIndex: 1,
    explanation: 'Tomás fue fraile dominico, teólogo y doctor de la Iglesia, conocido como Doctor Angélico.',
    source: 'Vatican News, Santos: santo Tomás de Aquino',
  },
  {
    id: 'santos-10',
    category: 'santos',
    prompt: '¿Cuál es la obra más conocida de santa Teresa de Jesús sobre el camino interior del alma?',
    options: ['Historia de un alma', 'Las Moradas o Castillo interior', 'Ejercicios espirituales', 'Diálogo de la divina providencia'],
    correctIndex: 1,
    explanation: 'Las Moradas describe el itinerario del alma hacia la unión con Dios mediante siete moradas.',
    source: 'Vatican News, Santos: santa Teresa de Jesús',
  },
  {
    id: 'santos-11',
    category: 'santos',
    prompt: '¿Con qué santa reformó san Juan de la Cruz la rama descalza del Carmelo?',
    options: ['Santa Catalina de Siena', 'Santa Teresa de Jesús', 'Santa Rosa de Lima', 'Santa Teresa de Lisieux'],
    correctIndex: 1,
    explanation: 'Juan de la Cruz colaboró con Teresa de Ávila en la reforma del Carmelo.',
    source: 'Vatican News, Santos: san Juan de la Cruz',
  },
  {
    id: 'santos-12',
    category: 'santos',
    prompt: '¿Quién fundó la Compañía de Jesús?',
    options: ['San Francisco Javier', 'San Ignacio de Loyola', 'San Felipe Neri', 'San Alfonso María de Ligorio'],
    correctIndex: 1,
    explanation: 'Ignacio de Loyola fundó la Compañía de Jesús y legó a la Iglesia los Ejercicios espirituales.',
    source: 'Vatican News, Santos: san Ignacio de Loyola',
  },
  {
    id: 'santos-13',
    category: 'santos',
    prompt: '¿En qué región desarrolló gran parte de su misión san Francisco Javier?',
    options: ['Escandinavia', 'Asia', 'África central', 'América del Norte'],
    correctIndex: 1,
    explanation: 'Francisco Javier evangelizó en India, el sudeste asiático y Japón, y murió camino a China.',
    source: 'Vatican News, Santos: san Francisco Javier',
  },
  {
    id: 'santos-14',
    category: 'santos',
    prompt: '¿Qué obra espiritual escribió san Ignacio de Loyola para ayudar al discernimiento y al encuentro con Dios?',
    options: ['La subida al monte Carmelo', 'Los Ejercicios espirituales', 'La imitación de Cristo', 'La regla pastoral'],
    correctIndex: 1,
    explanation: 'Los Ejercicios espirituales ordenan la oración y el discernimiento para buscar y hallar la voluntad de Dios.',
    source: 'Vatican News, Santos: san Ignacio de Loyola',
  },
  {
    id: 'santos-15',
    category: 'santos',
    prompt: '¿Qué espiritualidad caracteriza especialmente a santa Teresita del Niño Jesús?',
    options: ['La pequeña vía de confianza y amor', 'El retiro absoluto del mundo', 'El estudio exclusivo de la filosofía', 'La peregrinación permanente'],
    correctIndex: 0,
    explanation: 'Su «pequeña vía» enseña a confiar como hijos y ofrecer con amor las cosas pequeñas de cada día.',
    source: 'Vatican News, Santos: santa Teresa del Niño Jesús',
  },
  {
    id: 'santos-16',
    category: 'santos',
    prompt: '¿A quién ofreció san Maximiliano María Kolbe su vida en Auschwitz?',
    options: ['A un guardia enfermo', 'A otro prisionero condenado a morir', 'A un sacerdote recién llegado', 'A un familiar suyo'],
    correctIndex: 1,
    explanation: 'Kolbe se ofreció en lugar de Franciszek Gajowniczek, padre de familia condenado al búnker del hambre.',
    source: 'Vatican News, Santos: san Maximiliano María Kolbe',
  },
  {
    id: 'santos-17',
    category: 'santos',
    prompt: '¿Qué nombre religioso tomó la filósofa Edith Stein?',
    options: ['Teresa Benedicta de la Cruz', 'María Faustina del Santísimo Sacramento', 'Teresa de Calcuta', 'Benedicta de Asís'],
    correctIndex: 0,
    explanation: 'Edith Stein ingresó al Carmelo como Teresa Benedicta de la Cruz y murió mártir en Auschwitz.',
    source: 'Vatican News: Edith Stein, copatrona de Europa',
  },
  {
    id: 'santos-18',
    category: 'santos',
    prompt: '¿Qué congregación fundó santa Teresa de Calcuta?',
    options: ['Misioneras de la Caridad', 'Hermanitas de los Pobres', 'Siervas de María', 'Hijas de la Caridad'],
    correctIndex: 0,
    explanation: 'Fundó las Misioneras de la Caridad para servir a Cristo en los más pobres entre los pobres.',
    source: 'Vatican News, Santos: santa Teresa de Calcuta',
  },
  {
    id: 'santos-19',
    category: 'santos',
    prompt: '¿A qué orden perteneció san Pío de Pietrelcina, conocido como Padre Pío?',
    options: ['Carmelitas', 'Capuchinos', 'Salesianos', 'Agustinos'],
    correctIndex: 1,
    explanation: 'Padre Pío fue sacerdote capuchino y dedicó innumerables horas a la Eucaristía y la confesión.',
    source: 'Vatican News, Santos: san Pío de Pietrelcina',
  },
  {
    id: 'santos-20',
    category: 'santos',
    prompt: '¿En qué país nació san Juan Pablo II?',
    options: ['Italia', 'Polonia', 'Croacia', 'Eslovaquia'],
    correctIndex: 1,
    explanation: 'Karol Józef Wojtyła nació en Wadowice, Polonia, en 1920.',
    source: 'Vaticano, biografía de san Juan Pablo II',
  },
  {
    id: 'santos-21',
    category: 'santos',
    prompt: '¿Qué devoción difundió especialmente santa Faustina Kowalska?',
    options: ['La Divina Misericordia', 'El escapulario del Carmen', 'El rosario de las siete alegrías', 'La medalla de san Benito'],
    correctIndex: 0,
    explanation: 'Su Diario transmite la llamada de Cristo a confiar en su misericordia y practicarla con el prójimo.',
    source: 'Vatican News, Santos: santa Faustina Kowalska',
  },
  {
    id: 'santos-22',
    category: 'santos',
    prompt: '¿En qué lugar se apareció la Virgen a santa Bernadette Soubirous?',
    options: ['Fátima', 'Lourdes', 'La Salette', 'Guadalupe'],
    correctIndex: 1,
    explanation: 'Bernadette recibió las apariciones en la gruta de Massabielle, en Lourdes.',
    source: 'Vatican News, Santos: santa Bernadette Soubirous',
  },
  {
    id: 'santos-23',
    category: 'santos',
    prompt: '¿Qué imagen quedó impresa en la tilma de san Juan Diego?',
    options: ['Nuestra Señora de Guadalupe', 'Nuestra Señora de Fátima', 'Nuestra Señora de Lourdes', 'Nuestra Señora del Carmen'],
    correctIndex: 0,
    explanation: 'La tradición guadalupana relata que la imagen de la Virgen quedó en su tilma al presentar las rosas al obispo.',
    source: 'Vaticano, canonización de san Juan Diego',
  },
  {
    id: 'santos-24',
    category: 'santos',
    prompt: '¿Qué aspecto de la fe procuró difundir el beato Carlo Acutis mediante internet?',
    options: ['Los milagros eucarísticos', 'La arquitectura de catedrales', 'Los manuscritos medievales', 'Las peregrinaciones a Tierra Santa'],
    correctIndex: 0,
    explanation: 'Carlo creó una exposición digital sobre milagros eucarísticos como fruto de su amor a la Eucaristía.',
    source: 'Vaticano, canonización de san Carlo Acutis; Vatican News, exposición de milagros eucarísticos',
  },
  {
    id: 'santos-25',
    category: 'santos',
    prompt: '¿Cuál fue la primera santa de Chile?',
    options: ['Beata Laura Vicuña', 'Santa Teresa de los Andes', 'Santa Rosa de Lima', 'Santa Nazaria Ignacia'],
    correctIndex: 1,
    explanation: 'Juanita Fernández Solar, carmelita descalza, fue canonizada como santa Teresa de los Andes en 1993.',
    source: 'Vatican News: centenario de santa Teresa de los Andes',
  },

  {
    id: 'san-josemaria-01',
    category: 'san-josemaria',
    prompt: '¿En qué ciudad nació san Josemaría Escrivá?',
    options: ['Madrid', 'Zaragoza', 'Barbastro', 'Pamplona'],
    correctIndex: 2,
    explanation: 'San Josemaría nació en Barbastro, provincia de Huesca, el 9 de enero de 1902.',
    source: 'Vaticano, biografía para la canonización de san Josemaría',
  },
  {
    id: 'san-josemaria-02',
    category: 'san-josemaria',
    prompt: '¿En qué fecha nació san Josemaría?',
    options: ['9 de enero de 1902', '26 de junio de 1902', '2 de octubre de 1902', '14 de febrero de 1903'],
    correctIndex: 0,
    explanation: 'Nació el 9 de enero de 1902 y fue bautizado cuatro días después.',
    source: 'Opus Dei, cronología de san Josemaría',
  },
  {
    id: 'san-josemaria-03',
    category: 'san-josemaria',
    prompt: '¿Qué huellas despertaron en el joven Josemaría el presentimiento de una llamada de Dios?',
    options: ['Las de un peregrino descalzo', 'Las de un carmelita descalzo sobre la nieve', 'Las de su padre en el barro', 'Las de un pastor en el monte'],
    correctIndex: 1,
    explanation: 'Al ver las huellas de un carmelita descalzo en la nieve, pensó que Dios podía pedirle algo.',
    source: 'Opus Dei, biografía de san Josemaría',
  },
  {
    id: 'san-josemaria-04',
    category: 'san-josemaria',
    prompt: '¿En qué año fue ordenado sacerdote san Josemaría?',
    options: ['1918', '1925', '1928', '1934'],
    correctIndex: 1,
    explanation: 'Fue ordenado sacerdote en Zaragoza el 28 de marzo de 1925.',
    source: 'Opus Dei, cronología de san Josemaría',
  },
  {
    id: 'san-josemaria-05',
    category: 'san-josemaria',
    prompt: '¿En qué fecha fundó san Josemaría el Opus Dei?',
    options: ['14 de febrero de 1930', '2 de octubre de 1928', '26 de junio de 1975', '6 de octubre de 2002'],
    correctIndex: 1,
    explanation: 'Durante unos ejercicios espirituales, el 2 de octubre de 1928, vio la misión que Dios le confiaba.',
    source: 'Vaticano, biografía para la canonización de san Josemaría',
  },
  {
    id: 'san-josemaria-06',
    category: 'san-josemaria',
    prompt: '¿Qué significa «Opus Dei» en latín?',
    options: ['Camino de santidad', 'Obra de Dios', 'Pueblo de Dios', 'Servicio de la Iglesia'],
    correctIndex: 1,
    explanation: 'Opus Dei significa «Obra de Dios», nombre que expresa la iniciativa divina de su misión.',
    source: 'Opus Dei, historia de la institución',
  },
  {
    id: 'san-josemaria-07',
    category: 'san-josemaria',
    prompt: '¿Qué comprendió san Josemaría el 14 de febrero de 1930?',
    options: ['Que debía trasladarse a Roma', 'Que el Opus Dei también era para las mujeres', 'Que debía escribir Camino', 'Que debía fundar una universidad'],
    correctIndex: 1,
    explanation: 'Ese día comprendió que las mujeres también debían formar parte del Opus Dei.',
    source: 'Opus Dei, cronología de san Josemaría',
  },
  {
    id: 'san-josemaria-08',
    category: 'san-josemaria',
    prompt: '¿Qué fundó san Josemaría el 14 de febrero de 1943?',
    options: ['La Sociedad Sacerdotal de la Santa Cruz', 'La Academia DYA', 'La Universidad de Navarra', 'El santuario de Torreciudad'],
    correctIndex: 0,
    explanation: 'La Sociedad Sacerdotal de la Santa Cruz hizo posible la ordenación de sacerdotes procedentes de los fieles laicos del Opus Dei.',
    source: 'Opus Dei, cronología de san Josemaría',
  },
  {
    id: 'san-josemaria-09',
    category: 'san-josemaria',
    prompt: '¿Cuál es el núcleo del mensaje que difundió san Josemaría?',
    options: ['La santidad está reservada a religiosos', 'Todos están llamados a la santidad en la vida ordinaria', 'Solo el estudio teológico conduce a Dios', 'La vida cristiana exige abandonar el trabajo civil'],
    correctIndex: 1,
    explanation: 'Recordó la llamada universal a la santidad y el encuentro con Dios en el trabajo y los deberes cotidianos.',
    source: 'Vaticano, el mensaje de san Josemaría',
  },
  {
    id: 'san-josemaria-10',
    category: 'san-josemaria',
    prompt: 'Según su enseñanza, ¿qué puede llegar a ser el trabajo realizado por amor a Dios?',
    options: ['Una distracción necesaria', 'Una oración y camino de santidad', 'Una actividad ajena a la fe', 'Una obligación reservada a algunos'],
    correctIndex: 1,
    explanation: 'El trabajo honesto puede santificarse, santificar a quien lo realiza y servir a los demás.',
    source: 'Vaticano, homilía de canonización de san Josemaría',
  },
  {
    id: 'san-josemaria-11',
    category: 'san-josemaria',
    prompt: '¿Cómo se llamó la primera academia-residencia impulsada por san Josemaría en Madrid?',
    options: ['DYA', 'Tajamar', 'Moncloa', 'Torreciudad'],
    correctIndex: 0,
    explanation: 'La Academia DYA comenzó en 1933 y luego se convirtió en residencia universitaria.',
    source: 'Opus Dei, historia: la Academia DYA',
  },
  {
    id: 'san-josemaria-12',
    category: 'san-josemaria',
    prompt: '¿Cuántos puntos breves contiene Camino?',
    options: ['365', '500', '999', '1000'],
    correctIndex: 2,
    explanation: 'Camino reúne 999 consideraciones para la oración y la vida cristiana.',
    source: 'Opus Dei, Camino, Surco y Forja',
  },
  {
    id: 'san-josemaria-13',
    category: 'san-josemaria',
    prompt: '¿En qué año apareció la edición definitiva de Camino?',
    options: ['1934', '1939', '1946', '1968'],
    correctIndex: 1,
    explanation: 'Camino se publicó con ese título en Valencia en 1939, ampliando Consideraciones espirituales.',
    source: 'Opus Dei, Camino, Surco y Forja',
  },
  {
    id: 'san-josemaria-14',
    category: 'san-josemaria',
    prompt: '¿Qué libro anterior fue el antecedente directo de Camino?',
    options: ['Santo Rosario', 'Consideraciones espirituales', 'Amigos de Dios', 'Conversaciones'],
    correctIndex: 1,
    explanation: 'Consideraciones espirituales apareció en 1934 y fue ampliado hasta formar Camino.',
    source: 'Opus Dei, Camino, Surco y Forja',
  },
  {
    id: 'san-josemaria-15',
    category: 'san-josemaria',
    prompt: '¿Cuál de estas obras de san Josemaría fue publicada póstumamente en 1986?',
    options: ['Camino', 'Surco', 'Conversaciones', 'Es Cristo que pasa'],
    correctIndex: 1,
    explanation: 'Surco fue preparado por san Josemaría y se publicó después de su muerte, en 1986.',
    source: 'Opus Dei, Camino, Surco y Forja',
  },
  {
    id: 'san-josemaria-16',
    category: 'san-josemaria',
    prompt: '¿Qué libro de san Josemaría, publicado en 1987, se organiza como un itinerario de vida interior?',
    options: ['Forja', 'Santo Rosario', 'La Abadesa de las Huelgas', 'Via Crucis'],
    correctIndex: 0,
    explanation: 'Forja reúne 1.055 puntos distribuidos en capítulos que recorren el proceso de la vida cristiana.',
    source: 'Opus Dei, Camino, Surco y Forja',
  },
  {
    id: 'san-josemaria-17',
    category: 'san-josemaria',
    prompt: '¿Qué breve obra escribió san Josemaría para ayudar a contemplar los misterios del Rosario?',
    options: ['Santo Rosario', 'Conversaciones', 'Surco', 'Amar a la Iglesia'],
    correctIndex: 0,
    explanation: 'Santo Rosario nació de su oración personal y fue publicado por primera vez en 1934.',
    source: 'Opus Dei, obras completas de san Josemaría',
  },
  {
    id: 'san-josemaria-18',
    category: 'san-josemaria',
    prompt: '¿En qué año se trasladó san Josemaría a vivir a Roma?',
    options: ['1936', '1939', '1946', '1950'],
    correctIndex: 2,
    explanation: 'En 1946 fijó su residencia en Roma, desde donde impulsó la expansión apostólica del Opus Dei.',
    source: 'Opus Dei, cronología de san Josemaría',
  },
  {
    id: 'san-josemaria-19',
    category: 'san-josemaria',
    prompt: '¿Dónde murió san Josemaría el 26 de junio de 1975?',
    options: ['Madrid', 'Pamplona', 'Roma', 'Barbastro'],
    correctIndex: 2,
    explanation: 'Murió en Roma, en la sede central del Opus Dei, después de regresar de Castelgandolfo.',
    source: 'Vaticano, biografía para la canonización de san Josemaría',
  },
  {
    id: 'san-josemaria-20',
    category: 'san-josemaria',
    prompt: '¿En qué fecha celebra la Iglesia la memoria litúrgica de san Josemaría?',
    options: ['9 de enero', '14 de febrero', '26 de junio', '2 de octubre'],
    correctIndex: 2,
    explanation: 'Su memoria litúrgica se celebra el 26 de junio, aniversario de su muerte.',
    source: 'Calendario litúrgico; Vaticano, san Josemaría Escrivá',
  },
  {
    id: 'san-josemaria-21',
    category: 'san-josemaria',
    prompt: '¿Qué papa beatificó a san Josemaría en 1992?',
    options: ['San Pablo VI', 'San Juan Pablo II', 'Benedicto XVI', 'Francisco'],
    correctIndex: 1,
    explanation: 'San Juan Pablo II lo beatificó en Roma el 17 de mayo de 1992.',
    source: 'Vaticano, cronología de la canonización de san Josemaría',
  },
  {
    id: 'san-josemaria-22',
    category: 'san-josemaria',
    prompt: '¿Cuándo fue canonizado san Josemaría?',
    options: ['6 de octubre de 2002', '17 de mayo de 1992', '26 de junio de 1975', '2 de octubre de 1928'],
    correctIndex: 0,
    explanation: 'San Juan Pablo II lo canonizó en la plaza de San Pedro el 6 de octubre de 2002.',
    source: 'Vaticano, canonización de san Josemaría',
  },
  {
    id: 'san-josemaria-23',
    category: 'san-josemaria',
    prompt: '¿Con qué advocación mariana se relaciona el santuario promovido por san Josemaría en Torreciudad?',
    options: ['Nuestra Señora de los Ángeles', 'Nuestra Señora de Torreciudad', 'Nuestra Señora del Pilar', 'Nuestra Señora de Loreto'],
    correctIndex: 1,
    explanation: 'San Josemaría promovió el nuevo santuario junto a la antigua ermita de Nuestra Señora de Torreciudad.',
    source: 'Opus Dei, biografía de san Josemaría; Santuario de Torreciudad',
  },
  {
    id: 'san-josemaria-24',
    category: 'san-josemaria',
    prompt: '¿Qué lugar ocupa la Santa Misa en la vida cristiana según una expresión repetida por san Josemaría?',
    options: ['Es una devoción opcional entre otras', 'Es el centro y la raíz de la vida interior', 'Es únicamente una obligación dominical', 'Es un acto reservado a los sacerdotes'],
    correctIndex: 1,
    explanation: 'Enseñó a hacer de la Santa Misa el centro y la raíz de la vida interior.',
    source: 'San Josemaría, Es Cristo que pasa, n. 87',
  },
  {
    id: 'san-josemaria-25',
    category: 'san-josemaria',
    prompt: '¿Qué expresión resume la presencia cristiana que san Josemaría proponía en medio del mundo?',
    options: ['Contemplativos en medio del mundo', 'Monjes sin monasterio', 'Estudiosos sin descanso', 'Peregrinos sin hogar'],
    correctIndex: 0,
    explanation: 'Invitó a ser contemplativos en medio del mundo, encontrando a Dios en las ocupaciones ordinarias.',
    source: 'San Josemaría, Conversaciones, n. 114',
  },
] as const;

const legacyInitialQuestionIds = new Set([
  'jesus-01', 'jesus-03', 'jesus-04', 'jesus-05', 'jesus-07', 'jesus-09', 'jesus-11', 'jesus-12', 'jesus-20',
  'antiguo-testamento-01', 'antiguo-testamento-02', 'antiguo-testamento-03', 'antiguo-testamento-04',
  'antiguo-testamento-07', 'antiguo-testamento-09', 'antiguo-testamento-10', 'antiguo-testamento-11', 'antiguo-testamento-17',
  'santos-01', 'santos-02', 'santos-03', 'santos-06', 'santos-12', 'santos-18', 'santos-20', 'santos-22', 'santos-25',
  'san-josemaria-01', 'san-josemaria-02', 'san-josemaria-05', 'san-josemaria-06', 'san-josemaria-09',
  'san-josemaria-10', 'san-josemaria-19', 'san-josemaria-20', 'san-josemaria-22',
]);

const legacyAdvancedQuestionIds = new Set([
  'jesus-06', 'jesus-13', 'jesus-15', 'jesus-16', 'jesus-19', 'jesus-21', 'jesus-24', 'jesus-25',
  'antiguo-testamento-05', 'antiguo-testamento-08', 'antiguo-testamento-14', 'antiguo-testamento-18',
  'antiguo-testamento-20', 'antiguo-testamento-22', 'antiguo-testamento-23', 'antiguo-testamento-24',
  'santos-05', 'santos-07', 'santos-10', 'santos-11', 'santos-14', 'santos-16', 'santos-17', 'santos-24',
  'san-josemaria-07', 'san-josemaria-08', 'san-josemaria-11', 'san-josemaria-12',
  'san-josemaria-13', 'san-josemaria-14', 'san-josemaria-15', 'san-josemaria-16',
]);

const originalQuestionsWithDifficulty: readonly TriviaQuestion[] = originalSpiritualTriviaQuestions.map((question) => ({
  ...question,
  difficulty: legacyInitialQuestionIds.has(question.id)
    ? 'inicial'
    : legacyAdvancedQuestionIds.has(question.id)
      ? 'avanzada'
      : 'intermedia',
}));

export const spiritualTriviaQuestions: readonly TriviaQuestion[] = [
  ...originalQuestionsWithDifficulty,
  ...additionalSpiritualTriviaQuestions,
];
